services:
  crudsupermercado: 
    build: crudsupermercado 
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://basedatos:3306/crudsupermercado?createDataBaseIfNotExist=true&serverTimezone=UTC  
      DB_USER_NAME: root 
      DB_PASSWORD:  
    restart: always
    depends_on:
      basedatos:    
          condition: service_healthy
  basedatos: 
    image: mysql:8.0.33 
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_PASSWORD:       
      MYSQL_DATABASE: crudsupermercado  
    restart: always  
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]   
      timeout: 10s
      retries: 10